spring:
  application:
    name: mscartoes

server:
  port: 0

eureka:
  client:
    service-url:
      instanceZone: http://localhost:8761:eureka
  instance:
#    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}